
############################################################
# Dockerfile to build sandbox for executing user code
# Based on Ubuntu
############################################################

FROM ubuntu:latest

RUN apt-get -y update

RUN apt-get install -y gcc
RUN apt-get install -y g++

RUN apt-get install -y vim

RUN apt-get install -y curl
RUN apt-get install -y wget

RUN apt-get install -y bc
RUN apt-get install time