import "../styles/globals.css";
import Layout from "@/components/Shared/Layout/Layout";
import Providers from "@/redux/provider";
import { Outfit } from "next/font/google";
import { Theme } from "@/components/Theme";

const outfit = Outfit({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { PropsWithChildren } from "react";
import { RootStyleRegistry } from "./lib/antd";
import React from "react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
        <RootStyleRegistry>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
